FROM hub.c.163.com/library/tomcat:8.0-jre7

ADD http://demo.nos-eastchina1.126.net/springblog.war /usr/local/tomcat/webapps/springblog.war

ADD http://demo.nos-eastchina1.126.net/spring-instrument-tomcat-4.2.2.RELEASE.jar /usr/local/tomcat/lib/spring-instrument-tomcat-4.2.2.RELEASE.jar

RUN chmod 644 /usr/local/tomcat/webapps/springblog.war

RUN chmod 644 /usr/local/tomcat/lib/spring-instrument-tomcat-4.2.2.RELEASE.jar

ENTRYPOINT catalina.sh run
